import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { rubik } from "@/ui/fonts";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	                                   children,
                                   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" dir="rtl">
		<body className={`${rubik.className} antialiased`}>
		<Navbar/>
		<main className='flex flex-col min-h-[calc(100vh-6rem-1px)]'>
			<div className="flex flex-1 flex-col h-full">{children}</div>
			<Footer />
		</main>
		<Toaster />
		</body>
		</html>
	);
}
